//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int studentID { get; set; }
        public string studentName { get; set; }
        public string studentSurname { get; set; }
        public string studentEmail { get; set; }
        public string studentPhoto { get; set; }
        public string studentAddress { get; set; }
    }
}
